root ::= object | array
sign ::= ("+" | "-")?
fraction ::= ("." [\d]+)?
exponent ::= ([eE] sign [\d]+)?
hex_digit ::= [a-fA-F\d]
escape ::= ["\/bfnrt] | "u" hex_digit hex_digit hex_digit hex_digit
string_characters ::= #x22 | [^#x0-#x1f"#x5c] string_characters | "\\" escape string_characters
string ::= #x22 string_characters
number ::= "0" fraction exponent | [1-9] [\d]* fraction exponent | "-" "0" fraction exponent | "-" [1-9] [\d]* fraction exponent
value ::= object | array | string | number | "true" | "false" | "null"
member ::= string [ \n\t]* ":" [ \n\t]* value
members ::= member ([ \n\t]* "," [ \n\t]* member)*
object ::= "{" [ \n\t]* (members [ \n\t]*)? "}"
elements ::= value ([ \n\t]* "," [ \n\t]* value)*
array ::= "[" [ \n\t]* (elements [ \n\t]*)? "]"