root = object | array;
sign = ['+' | '-'];
fraction = ['.', '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9', {'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'}];
exponent = ['e' | 'E', sign, '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9', {'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'}];
hex_digit = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
escape = '"' | '/' | 'b' | 'f' | 'n' | 'r' | 't' | 'u', 4 * hex_digit;
string_characters = '"' | ' ' | '!' | '#' | '$' | '%' | '&' | '\'' | '(' | ')' | '*' | '+' | ',' | '-' | '.' | '/' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | ':' | ';' | '<' | '=' | '>' | '?' | '@' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '[' | '\\' | ']' | '^' | '_' | '`' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | '{' | '|' | '}' | '~', string_characters | '\\', escape, string_characters;
string = '"', string_characters;
number = '0', fraction, exponent | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9', {'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'}, fraction, exponent | '-', '0', fraction, exponent | '-', '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9', {'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'}, fraction, exponent;
value = object | array | string | number | 'true' | 'false' | 'null';
member = string, {' ' | '
' | '	'}, ':', {' ' | '
' | '	'}, value;
members = member, {({' ' | '
' | '	'}, ',', {' ' | '
' | '	'}, member)};
object = '{', {' ' | '
' | '	'}, [members, {' ' | '
' | '	'}], '}';
elements = value, {({' ' | '
' | '	'}, ',', {' ' | '
' | '	'}, value)};
array = '[', {' ' | '
' | '	'}, [elements, {' ' | '
' | '	'}], ']';