<root> ::= <value>
<value> ::= <object> | <array> | <string> | <number> | "true" | "false" | "null"
<object> ::= "{" [<members>] "}"
<members> ::= <pair> <members__bnf_1>
<members__bnf_1> ::= "" | "," <pair> <members__bnf_1>
<pair> ::= <string> ":" <value>
<array> ::= "[" [<elements>] "]"
<elements> ::= <value> <elements__bnf_1>
<elements__bnf_1> ::= "" | "," <value> <elements__bnf_1>
<string> ::= "string"
<number> ::= <integer> [<fraction>] [<exponent>]
<integer> ::= <digit> <integer__bnf_1>
<integer__bnf_1> ::= "" | <digit> <integer__bnf_1>
<fraction> ::= "." <digit> <fraction__bnf_1>
<fraction__bnf_1> ::= "" | <digit> <fraction__bnf_1>
<exponent> ::= "e" [<sign>] <digit> <exponent__bnf_1> | "E" [<sign>] <digit> <exponent__bnf_1>
<exponent__bnf_1> ::= "" | <digit> <exponent__bnf_1>
<sign> ::= "+" | "-"
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"